# Definitions
build_tool = runtime-container.DONE
name = quay.io/ucsc_cgl/rnaseq-cgl-pipeline
git_commit ?= $(shell git log --pretty=oneline -n 1 -- ../../rnaseq-cgl-pipeline | cut -f1 -d " ")
short_tag = 2.0.10--DOCKERVER
long_tag = ${tag}--${git_commit}

build: Dockerfile
	docker build -t ${name}:${long_tag} .
	docker tag -f ${name}:${long_tag} ${name}:${short_tag}
	touch ${build_tool}

push: build
	# Requires ~/.dockercfg
	docker push ${name}:${long_tag}
	docker push ${name}:${short_tag}

test: build
	python test.py ${tag}

clean:
	docker rmi -f ${name}:${tag}
	rm ${build_tool}
